---
- hosts: all
  become: yes
  become_user: root
  vars:
        download_url: "http://bnalmsat702.medhost.com/pub/chronyplugin/nrpe.cfg"       
        
        
  tasks:

      - name: Copy new nrpe file to clients
        copy:
            src: /Users/wmendoza/Ansible/playbooks/nagios/nrpe.cfg
            dest: /usr/local/nagios/etc/nrpe.cfg
            owner: root
            group: root
            mode: '0644'
            backup: yes

      - name: Restart xinetd service
        command: "service xinetd restart"

        ignore_errors: yes
