---
- hosts: all
  become: yes
  become_user: root
  vars:
          download_url: "http://bnalmsat701.corp.local/pub/nagios_user"
          download_archive:  "{{download_folder}}nagios_user"
          download_folder: /home/htadmin/
          
          
        
        
  tasks:
        - name: Uninstall Beacon 
          shell: yum remove nrpe < <(yes y)               

        - name: Remove nagios user
          shell: userdel nagios


        - name: Un-install /etc/nagios
          shell: rm -rf /etc/nagios
        
        - name: Remove /home/nagios
          shell: rm -rf /home/nagios

        - name: Remove /usr/local/nagios
          shell: rm -rf /usr/local/nagios

        - name: Remove old linux-nrpe-agent 
          shell: rm -rf /home/htadmin/linux-nrpe-agent*

        - name: Remove plugins folder
          shell: rm -rf /home/htadmin/plugins*
          ignore_errors: yes
