---
- hosts: epops
  become: yes
  become_user: root
       
        
        
  tasks:

      -  name: Copy vRops epops-agent rpm 
         copy:
            src: /var/www/html/pub/epops-agent/vRealize-Endpoint-Operations-Management-Agent-x86-64-linux-7.5.0-13055136.rpm
            dest: /root/vRealize-Endpoint-Operations-Management-Agent-x86-64-linux-7.5.0-13055136.rpm
            owner: root
            group: root
            mode: '0644'
      
      -  name: Install the epops-agent rpm
         yum:
             name: /root/vRealize-Endpoint-Operations-Management-Agent-x86-64-linux-7.5.0-13055136.rpm
             state: present

      -  name: Copy new agent.properties file 
         copy:
            src: /var/www/html/pub/epops-agent/agent.properties
            dest: /opt/vmware/epops-agent/conf/agent.properties
            owner: epops
            group: epops
            mode: '0600'
            backup: no

      -  name: Change folder permissions
         file:
            path: /opt/vmware
            owner: epops
            group: epops

      -  name: start epop service
         service:
            name: epops-agent
            pattern: /opt/vmware/epops-agent/bin/ep-agent.sh
            state: started

      -  name: Remove the epops-agent RPM
         file:
            name: vRealize-Endpoint-Operations-Management-Agent-x86-64-linux-7.5.0-13055136.rpm
            path: /root/
            state: absent

         ignore_errors: yes
